all:
	gcc .\src\logtables.c -o .\bin\logtables.exe
	gcc .\src\string_input.c -o .\bin\string_input.exe
	gcc .\src\strcmp_play.c -o .\bin\strcmp_play.exe
	gcc .\src\wurzel.c -o .\bin\wurzel.exe
	gcc .\src\quadratic_eq.c -o .\bin\quadratic_eq.exe
	gcc .\src\weekdays.c -o .\bin\weekdays.exe