# This is the standard procedure to create the executables
all:
	gcc .\src\InOut.c -o .\bin\InOut.exe
	gcc .\src\physicsexample.c -o .\bin\physicsexample.exe
	gcc .\src\banking\bank_account_float.c -o .\bin\bank_account_float.exe
	gcc .\src\banking\bank_account_integer.c -o .\bin\bank_account_integer.exe
clear:
	rm .\bin\*