all:
	gcc .\src\statistics.c -o .\bin\statistics.exe
	gcc .\src\vectors.c -o .\bin\vectors.exe
	gcc .\src\unit_mat.c -o .\bin\unit_mat.exe
	gcc .\src\file_write.c -o .\bin\file_write.exe
	gcc .\src\file_read.c -o .\bin\file_read.exe
	gcc .\src\filter.c -o .\bin\filter.exe